python main.py p1
python main.py p2
python main.py p3
python main.py p4
python main.py p3
python main.py p3
python main.py p4
python main.py p5
python main.py p6
python main.py p7
python main.py p8
python main.py p9
python main.py p10
python main.py p11
python main.py p12
python main.py p13
python main.py p14
python main.py p15
python main.py p16
python main.py p17
python main.py p18
python main.py p19
python main.py p20
python main.py p21
python main.py p22
python main.py p23
python main.py p24
python main.py p25
python main.py p26
python main.py p27
python main.py p28
python main.py p29
python main.py p30
python main.py p31
python main.py p32
python main.py p33
python main.py p34
python main.py p35
python main.py p36
python main.py p37
python main.py p38
python main.py p39
python main.py p40
python main.py p41
python main.py p42
python main.py p43
python main.py p44
python main.py p45
python main.py p46
python main.py p47
python main.py p48
python main.py p49
python main.py p50
python main.py p51
python main.py p52
python main.py p53
python main.py p54
python main.py p55
python main.py p56
python main.py p57
python main.py p58
python main.py p59
python main.py p60
python main.py p61
python main.py p62
python main.py p63
python main.py p64
python main.py p65
python main.py p66
python main.py p67
python main.py p68
python main.py p69
python main.py p70
python main.py p71
pause